Fix errors

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -14,23 +14,12 @@ jobs:
     name: Test (${{ matrix.runs-on }})
     runs-on: ${{ matrix.runs-on }}
     steps:
-      - name: Checkout root directory
-        uses: actions/checkout@v4
-        with:
-          # Repository with crate in root and crate in subdirectory
-          repository: 'mondeja/cucumber-thirtyfour-worlder'
-      - name: Contains a line starting with 'version ='
+      - name: Prepare file
+        shell: bash
         run: |
-          if ! grep -q '^version =' Cargo.toml; then
-            echo "Error: Cargo.toml does not contain a line starting with 'version ='" >&2
-            exit 1
-          fi
-      - name: Not contains a line starting with 'foobar ='
-        run: |
-          if grep -q '^foobar =' Cargo.toml; then
-            echo "Error: Cargo.toml contains a line starting with 'foobar ='" >&2
-            exit 1
-          fi
+          echo '[package]' > Cargo.toml
+          echo 'version = "0.1.0"' >> Cargo.toml
+          echo 'foobar = "0.2.0"' >> Cargo.toml
       - name: Replace line starting with 'version =' with 'foobar = 0.0.0'
         uses: mondeja/starts-with-line-replacer@main
         with:
@@ -38,8 +27,16 @@ jobs:
           starts-with: 'version ='
           replace-by: 'foobar = "0.0.0"'
       - name: Contains a line with the content 'foobar = 0.0.0'
+        shell: bash
         run: |
           if ! grep -q '^foobar = "0.0.0"$' Cargo.toml; then
             echo "Error: Cargo.toml does not contain a line with the content 'foobar = 0.0.0'" >&2
+            exit 1
+          fi
+      - name: Does not contain a line starting with 'version ='
+        shell: bash
+        run: |
+          if grep -q '^version =' Cargo.toml; then
+            echo "Error: Cargo.toml contains a line starting with 'version ='" >&2
             exit 1
           fi
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -25,15 +25,39 @@ runs:
       env:
         FILE: ${{ inputs.file }}
       run: |
-        # Ensure the file exists
-        [ -f "$FILE" ] || { echo "Error: File '$FILE' does not exist." >&2 && exit 1 }
+        # Ensure the arguments are provided
+        if [[ -z "$FILE" ]]; then
+          echo "Error: 'file' input is required." >&2
+          exit 1
+        fi
+        if [[ -z "${{ inputs.starts-with }}" ]]; then
+          echo "Error: 'starts-with' input is required." >&2
+          exit 1
+        fi
+        if [[ -z "${{ inputs.replace-by }}" ]]; then
+          echo "Error: 'replace-by' input is required." >&2
+          exit 1
+        fi
 
+        # Ensure the file exists
+        if [[ ! -f "$FILE" ]]; then
+          echo "Error: File '$FILE' does not exist." >&2
+          exit 1
+        fi
+      
         # Ensure a line starts with the specified string
-        if ! grep -q '^${{ inputs.starts-with }}' $FILE; then
+        if ! grep -q '^${{ inputs.starts-with }}' "$FILE"; then
           echo "Error: No lines start with the specified 'starts-with' string." >&2
           exit 1
         fi
 
         # Replace lines that start with the specified string
-        sed -i 's/^${{ inputs.starts-with }}.*/${{ inputs.replace-by }}/' "$FILE"
-
+        #
+        # On darwin, sed requires the -i option to be followed by an empty string,
+        # but this is not accepted by GNU sed.
+        if [[ "$OSTYPE" == "darwin"* ]]; then
+          sed_i_option='-i ""'
+        else
+          sed_i_option='-i'
+        fi
+        sed $sed_i_option 's/^${{ inputs.starts-with }}.*/${{ inputs.replace-by }}/' "$FILE"
